AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashEachMethods:
 Enabled: false
Style/HashTransformKeys:
 Enabled: false
Style/HashTransformValues:
 Enabled: false


Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented


Lint/RaiseException:
 Enabled: false
Lint/StructNewOverride:
 Enabled: false
